# Generated by Django 5.2.12 on 2026-03-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_cliente', models.CharField(choices=[('medico', 'Médico'), ('clinica', 'Clínica'), ('centro', 'Centro de salud'), ('paciente', 'Paciente particular')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('condicion_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identidad', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_muestra', models.CharField(choices=[('citologia', 'Citología'), ('biopsia', 'Biopsia')], max_length=20)),
                ('numero_muestra', models.CharField(blank=True, max_length=30, null=True)),
                ('medico', models.CharField(blank=True, max_length=150, null=True)),
                ('centro', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_toma', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('proceso', 'En proceso'), ('diagnosticada', 'Diagnosticada'), ('entregada', 'Entregada')], default='recibida', max_length=20)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_tercera_edad', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.muestra')),
            ],
        ),
    ]
