# Generated by Django 5.2.12 on 2026-03-21 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muestra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('proceso', 'En proceso'), ('enviada_doctora', 'Enviada a doctora'), ('diagnosticada', 'Diagnosticada'), ('resultado_emitido', 'Resultado emitido'), ('entregada', 'Entregada')], default='recibida', max_length=30),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='numero_muestra',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
