# Generated by Django 5.2.12 on 2026-03-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0004_muestra_cantidad_muestras_recibidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_citologias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_biopsia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('citologia', 'Citología'), ('biopsia', 'Biopsia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('pendiente', 'Pendiente'), ('cambio', 'Cambio'), ('entrega', 'Entrega')], default='ingreso', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='concepto_frecuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.conceptofrecuente'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_especimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.tipoespecimen'),
        ),
        migrations.CreateModel(
            name='TarifaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('citologia', 'Citología'), ('biopsia', 'Biopsia')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='core.cliente')),
                ('tipo_especimen', models.ForeignKey(blank=True, help_text='Solo aplica para biopsias.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.tipoespecimen')),
            ],
            options={
                'unique_together': {('cliente', 'tipo_servicio', 'tipo_especimen')},
            },
        ),
    ]
